# Generated by Django 5.0.1 on 2026-01-11 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='pdf_file',
        ),
    ]
