# Generated by Django 5.0.1 on 2026-01-03 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=20)),
                ('s_description', models.CharField(max_length=100)),
                ('s_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('e_id', models.ForeignKey(db_column='e_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.electrician')),
            ],
        ),
    ]
