# Generated by Django 5.0.1 on 2026-01-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='s_name',
            field=models.CharField(max_length=100),
        ),
    ]
