# Generated by Django 5.0.1 on 2026-01-09 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_service_s_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='e_id',
        ),
    ]
