# Generated by Django 5.0.1 on 2026-01-03 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_fullname', models.CharField(max_length=30)),
                ('a_login_id', models.CharField(max_length=30, unique=True)),
                ('a_password', models.CharField(max_length=100)),
                ('a_contact', models.CharField(max_length=15)),
                ('a_address', models.CharField(max_length=50)),
                ('a_email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_fullname', models.CharField(max_length=30)),
                ('c_login_id', models.CharField(max_length=30, unique=True)),
                ('c_password', models.CharField(max_length=100)),
                ('c_contact', models.CharField(max_length=15)),
                ('c_email', models.EmailField(max_length=254, unique=True)),
                ('c_address', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Electrician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_fullname', models.CharField(max_length=30)),
                ('e_login_id', models.CharField(max_length=30, unique=True)),
                ('e_password', models.CharField(max_length=100)),
                ('e_contact', models.CharField(max_length=15)),
                ('e_qualification', models.CharField(max_length=50)),
                ('e_address', models.CharField(max_length=50)),
                ('e_email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
