# Generated by Django 5.0.1 on 2026-01-14 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_electrician_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='c_address',
            field=models.CharField(max_length=150),
        ),
    ]
