# Generated by Django 5.0.1 on 2026-01-18 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='electrician_earning',
            field=models.IntegerField(default=0),
        ),
    ]
